#!/data/data/com.termux/files/usr/bin/bash

clear
kill_color=$'\e[0m'
command -v yt-dlp &>/dev/null || printf "\e[031m Please install yt-dlp manualy or run the the install.sh script again.\n$kill_color"

#uncomment me if you wish :)
#[[ -f ~/bin ]] || printf "\e[031m Please Run the the install.sh script.\n$kill_color"


echo -e "\e[031m" "          ▄▀▄     ▄▀▄"
echo -e "\e[031m" "         ▄█░░▀▀▀▀▀░░█▄"
echo -e "\e[031m" "     ▄▄  █░░░░░░░░░░░█  ▄▄"
echo -e "\e[031m" "    █▄▄█ █░░█░░┬░░█░░█ █▄▄█"
echo -e "\e[036m" "╔════════════════════════════════════════╗"                                                                          
echo -e "\e[032m" "║ ♚ Project Name : 🆃🅴🆁🅼🆄🆇-🆈🆃🅳™           ║"
echo -e "\e[032m" "║ ♚ Author : KhanSaad1275                ║"
echo -e "\e[032m" "║ ♚ Github : g̲i̲t̲h̲u̲b̲.̲c̲o̲m̲/̲k̲h̲a̲n̲s̲a̲a̲d̲1̲2̲7̲5̲/̲    ║"
echo -e "\e[032m" "║ ♚ Website : www.LearnTermux.tech       ║"
echo -e "\e[036m" "╠════════════════════════════════════════╝"
echo -e "\e[036m" "╠═▶ [𝗦𝗲𝗹𝗲𝗰𝘁 𝗔 𝗙𝗼𝗿𝗺𝗮𝘁]  ➳"
echo -e "\e[032m" "╠═▶ 1. Video (Mp4)"
echo -e "\e[032m" "╠═▶ 2. Music"
echo -e "\e[032m" "╠═▶ 3. Video 360p"
echo -e "\e[032m" "╠═▶ 4. Video 480p"
echo -e "\e[032m" "╠═▶ 5. Video 720p"
echo -e "\e[032m" "╠═▶ 6. Video 1080p"
echo -e "\e[032m" "╠═▶ 7. Video 2160p"
echo -e "\e[032m" "╠═▶ 8. Exit Termux-YTD" # Added
command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Download/%(title)s.%(ext)s -f'

#Edit From Oak Atsume 
printf "\e[032m ╚═:➤  $kill_color"
read option

if [[ -z $option ]];
then
	clear
	printf "\e[031m Please choose a option!\n$kill_color"
else
case $option in #Make Case list
	1)
	yt-dlp "-f best[ext=mp4]/best" $1
	;;
	2)
	yt-dlp "-f 140"  $1
	;;
	3)
	yt-dlp "-f best[height<=360]" $1
	;;
	4)
	yt-dlp "-f best[height<=480]" $1
	;;
	5)
	yt-dlp "-f best[height<=720" $1
	;;
	6)
	yt-dlp "-f best[height<=1080" $1
	;;
	7)
	yt-dlp "-f best[height<=2160" $1
	;;
	8)
	break
	;;
esac 
fi


#There's a cat on the code!!
#          ▄▀▄     ▄▀▄
#         ▄█░░▀▀▀▀▀░░█▄
#     ▄▄  █░░░░░░░░░░░█  ▄▄
#    █▄▄█ █░░█░░┬░░█░░█ █▄▄█

#Oh hey there It's me Oak I have no idea how yt-dlp works but i came across this github and saw the messy code and gave it a better look hope it helps :D 

#I wanted to mess a little with the Download code but didn't 

#email: Kamilohulau@gmail.com
#Date: Wed Dec  2 15:48:19 PST 2020#
#Project name : Termux-YTD#
#Github: https://github.com/khansaad1275/Termux-YTD#
